model:
  base_learning_rate: 1.0e-04
  target: models.reconmodels.ldm.models.diffusion.ddpm.ImageEmbeddingConditionedLatentDiffusion
  params:
    embedding_dropout: 0.25
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.0120
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "jpg"
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    conditioning_key: crossattn-adm
    scale_factor: 0.18215
    monitor: val/loss_simple_ema
    use_ema: False

    embedder_config:
      target: models.reconmodels.autoencoder.vae.CNN_VAE.CNN_VAE
      params:
        input_size: 1024
        image_channels: 1
        hidden_dim: 64
        layers: 2
        kernel_sizes: 
          - 7
          - 7
        strides: 
          - 4
          - 4
        group_nums: 16
        latent_dim: 3
        loss_type: MSE
        lambda_kl: 1.0
      lossconfig:
        target: torch.nn.Identity

    unet_config:
      target: models.reconmodels.ldm.modules.diffusionmodules.dpmmodels.model.Model
      params:
        ch: 128
        out_ch: 3
        ch_mult:
          - 1
          - 2
          - 4
          - 4
        num_res_blocks: 2
        attn_resolutions: [ ]
        dropout: 0.0
        resamp_with_conv: true
        in_channels: 3
        resolution: 64
        use_timestep: true
        use_linear_attn: false
        attn_type: "vanilla"

    first_stage_config:
      target: models.reconmodels.autoencoder.vae.CNN_VAE.CNN_VAE
      params:
        input_size: 1024
        image_channels: 1
        hidden_dim: 64
        layers: 2
        kernel_sizes: 
          - 7
          - 7
        strides: 
          - 4
          - 4
        group_nums: 16
        latent_dim: 3
        loss_type: MSE
        lambda_kl: 1.0
      lossconfig:
        target: torch.nn.Identity

    cond_stage_config: __is_first_stage__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 48
    num_workers: 5
    wrap: false
    train:
      target: taming.data.faceshq.CelebAHQTrain
      params:
        size: 256
    validation:
      target: taming.data.faceshq.CelebAHQValidation
      params:
        size: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True