model:
  base_learning_rate: 1.0e-04
  target: models.reconmodels.ldm.models.diffusion.ddpm.ImageEmbeddingConditionedLatentDiffusion
  params:
    embedding_dropout: 0.25
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.0120
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    image_size: 96
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn-adm
    scale_factor: 0.18215
    monitor: val/loss_simple_ema
    use_ema: False

    embedder_config:
      target: models.reconmodels.ldm.modules.encoders.modules.CLIPTextTransformer
      params:
        model: "ViT-L/14"

    noise_aug_config:
      target: models.reconmodels.ldm.modules.encoders.modules.NoiseAugmentation
      params:
        clip_stats_path: "checkpoints/karlo_models/ViT-L-14_stats.th"
        timestep_dim: 768
        noise_schedule_config:
          timesteps: 1000
          beta_schedule: squaredcos_cap_v2

    unet_config:
      target: models.reconmodels.ldm.modules.diffusionmodules.dpmmodels.Unet.UnetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32

    first_stage_config:
      target: models.reconmodels.ldm.models.autoencoder.CNN_VAE
      params:
        embed_dim: 3
        monitor: val/rec_loss
        ddconfig:
          attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 3
          resolution: 1024
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"