model:
  base_learning_rate: 1.0e-04
  base_learning_optimizer: "Adam"
  base_learning_schedule: "CosineAnnealingLR"
  target: models.reconmodels.autoencoder.vae.CNN_VAE.CNN_VAE
  params:
    input_size: 1024
    image_channels: 1
    hidden_dim: 64
    layers: 2
    kernel_sizes: 
      - 7
      - 7
    strides: 
      - 4
      - 4
    group_nums: 16
    latent_dim: 3
    loss_type: MSE
    lambda_kl: 1.0



