model:
  base_learning_rate: 1.0e-04
  base_learning_optimizer: "AdamW"
  base_learning_schedule: "CosineAnnealingLR"
  target: models.reconmodels.autoencoder.models.vae.CNN_VAE_v2.CNN_VAE
  params:
    ckpt_path: null
    vae_modal: 'aia0094_image'
    kl_weight: 0.1
    loss_type: 'MSE'

    dd_config:
      double_z: True
      z_channels: 8
      resolution: 1024
      in_channels: 1
      out_ch: 1
      ch: 16
      ch_mult: [1,2,2,2] # num_down = len(ch_mult)-1
      num_res_blocks: 4
      attn_resolutions: []
      dropout: 0.0

    # loss_config:
    #   target: models.reconmodels.autoencoder.modules.losses.contperceptual.LPIPS
    #   params:
    #     rec_loss_type: l2
    #     log_var_init: 0.0
    #     kl_weight: 0.000001
    #     perceptual_weight: 1.0

data:
  target: data.build.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 9
    wrap: false
    train:
      target: data.dataset.SolarDataset_v2.multimodal_dataset
      params:
        modal_list: 
          # - 'magnet'
          - '0211'
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 0
          - 4800
        time_step: 1
    validation:
      target: data.dataset.SolarDataset_v2.multimodal_dataset
      params:
        modal_list: 
          # - 'magnet'
          - '0211'
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 4800
          - 5136
        time_step: 1

lighting:
  trainer:
    # accelerator: "gpu"
    # devices: 2
    max_epochs: 200