model:
  base_learning_rate: 1.0e-04
  base_learning_optimizer: "AdamW"
  base_learning_schedule: "CosineAnnealingLR"
  target: models.reconmodels.ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    parameterization: "eps"
    linear_start: 0.00085
    linear_end: 0.0120
    log_every_t: 200
    timesteps: 100
    first_stage_key: "0094_image"
    cond_stage_key: "0094_image"
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    conditioning_key: concat
    scale_factor: 1
    monitor: val/loss_simple_ema
    use_ema: False

    unet_config:
      target: models.reconmodels.ldm.modules.diffusionmodules.dpmmodels.model.Model
      params:
        ch: 384
        out_ch: 3
        ch_mult:
          - 1
          - 2
          - 4
          - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0
        resamp_with_conv: true
        in_channels: 6
        resolution: 64
        use_timestep: true
        use_linear_attn: false
        attn_type: "vanilla"
    
    first_stage_config:
      target: models.reconmodels.autoencoder.models.vae.CNN_VAE_v2.CNN_VAE_two
      params:
        ckpt_path: null
        vae_modal: aia0094_image
        kl_weight: 0.1
        loss_type: 'MSE'

        dd_config:
          double_z: True
          z_channels: 32
          resolution: 1024
          in_channels: 8
          out_ch: 8
          ch: 32
          ch_mult: [1,2,2]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        first_stage_config:
          ckpt_path: null
          vae_modal: 'aia0094_image'
          kl_weight: 0.1
          loss_type: 'MSE'
          dd_config:
            double_z: True
            z_channels: 8
            resolution: 1024
            in_channels: 1
            out_ch: 1
            ch: 16
            ch_mult: [1,2,2,2]
            num_res_blocks: 2
            attn_resolutions: []
            dropout: 0.0

    cond_stage_config: __is_first_stage__


data:
  target: data.build.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 9
    wrap: false
    train:
      target: data.dataset.SolarDataset_v2.multimodal_dataset
      params:
        modal_list: 
          # - 'magnet'
          - '0094'
          - '0131'
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 0
          - 4800
        time_step: 1
    validation:
      target: data.dataset.SolarDataset_v2.multimodal_dataset
      params:
        modal_list: 
          # - 'magnet'
          - '0094'
          - '0131'
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 4800
          - 5265
        time_step: 1

lightning:
  trainer:
    # strategy: "ddp"
    accelerator: "gpu"
    # devices: 2
    max_epochs: 200
    # benchmark: True

  # callbacks:
  #   image_logger:
  #     target: train.utils.callback.ImageLogger
  #     params:
  #       batch_frequency: 5000
  #       max_images: 8
  #       increase_log_steps: False

  # logger:
  #   target: pytorch_lightning.loggers.TensorBoardLogger
  #   params:
  #     name: tensorboard_logs
  #     save_dir: logs

  