model:
  base_learning_rate: 1.0e-04
  base_learning_optimizer: "Adam"
  base_learning_schedule: "CosineAnnealingLR"
  target: models.reconmodels.autoencoder.models.vqvae.models.vqgan_double.VQVAE2Model
  params:
    ckpt_path: null
    vq_modal: 'hmi_image'
    embed_dim: 16
    n_embed: 8192

    ddconfig:
      double_z: false
      z_channels: 16
      resolution: 128
      in_channels: 8
      out_ch: 8
      ch: 32
      ch_mult: [1,2]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: models.reconmodels.autoencoder.modules.losses.vqdouble.VQDoubleLoss
      params:
        codebook_weight: 1.0
        pixelloss_weight: 1.0 
        classifier_weight: 1.0
        n_classes: 8192
        pixel_loss: 'l1'

    first_vq_model_config:
      target: models.reconmodels.autoencoder.models.vqvae.models.vqgan.VQTokenizer
      params:
        ckpt_path: 'checkpoints/reconmodels/vqvae/vqgan/hmi_2_hmi_codebook_8192_epoch=000002.ckpt'
        vq_modal: 'hmi_image'
        embed_dim: 8
        n_embed: 8192

        ddconfig:
          double_z: false
          z_channels: 8
          resolution: 1024
          in_channels: 1
          out_ch: 1
          ch: 32
          ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

        lossconfig:
          target: torch.nn.Identity


data:
  target: data.build.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 9
    wrap: false
    train:
      target: data.dataset.SolarDataset.multimodal_dataset
      params:
        modal_list: 
          - 'magnet'
          - '0094'
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 0
          - 5346720
        time_step: 1
    validation:
      target: data.dataset.SolarDataset.multimodal_dataset
      params:
        modal_list: 
          - 'magnet'
          - '0094'
        load_imgs: false
        enhance_list:
          - 1024
          - 0.5
          - 90
        time_interval: 
          - 5346720
          - 7452000
        time_step: 115200

lightning:

  trainer:
    accelerator: "gpu"
    devices: 4
    max_epochs: 1000

  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      save_last: true
      every_n_epochs: 1